### PR TITLE
Repo sync optimization and keepalive script infusion

### PR DESCRIPTION
**Pull request by rokibhasansagar**

### CODE REVIEW

**Review by manjotsidhu — COMMENTED** [review]
This looks fine, does the same optimization can be done for `remote_build.sh` ?

**Comment by rokibhasansagar** [comment]
> This looks fine, does the same optimization can be done for `remote_build.sh` ?

remote_build.sh eventually fetches this build.sh (as it is unified, I see)
So, both Pie and A10 builds can use this patch.

**Comment by manjotsidhu** [comment]
@AndroiableDroid waiting for your review

**Review by AndroiableDroid — APPROVED** [review]
LGTM

**Pull request merged**
