### PR TITLE
pb: Bring up Unified build support

### PR DESCRIPTION
**Pull request by AndroiableDroid**
Test for for official/beta & I didn't tested for unofficial or test builds

- [x] Test Build

- [x] Beta build

- [x] Official build

### CODE REVIEW

**Review by AndroiableDroid — COMMENTED** [review]
LGTM

**Comment by manjotsidhu** [comment]
@AndroiableDroid can you explain me `get_device_name` and `get_vendor` functions ?

**Review by manjotsidhu — APPROVED** [review]
LGTM

**Comment by manjotsidhu** [comment]
@AndroiableDroid any updates ?

**Comment by AndroiableDroid** [comment]
> @AndroiableDroid any updates ?

Most probably today

**Review by manjotsidhu — APPROVED** [review]

**Pull request merged**
